module.exports = {
  content: ['index.html', 'assets/js/script.js'],
  css: ['assets/css/style.css'],
  output: 'dist/assets/css/style.css',
  safelist: {
    standard: [
      'show',
      'open',
      'hidden',
      'active',
      'flipped',
      'hero-confetti',
      'hero-doodle-svg',
      'settle-final',
      'floating-doodle',
      'floating-doodle-inner',
      'floating-doodle-squashed',
      'is-visible',
      'titre-1',
      'titre-2',
      'titre-3',
      'text-charte',
      'description-charte',
      'slider-active',
      'match-slider-container',
      'match-slider-track',
      'match-slide',
      'match-slide-image',
      'match-slide-overlay',
      'match-slide-name',
      'match-slide-name-line',
      'match-slide-name-line--first',
      'match-slide-name-line--second',
      'match-slide-role',
      'match-slide-bio',
      'match-slider-close',
      'match-slider-dots',
      'match-slider-dot',
      'spectacle-single-slide',
      'match-slide-bg-right',
      'match-slide-format-long-intro',
      'match-slide-match-intro',
      'match-slider-light-slide',
      'match-player-bio-layer',
      'match-player-bio-layer-close',
      'match-player-bio-layer-inner',
      'match-player-bio-layer-name',
      'match-player-bio-layer-text',
      'match-player-bio-open',
      'match-slide-name--has-bio',
      'match-slide-bio-short',
      'match-slide-bio-full',
      'tooltip-overlay',
      'tooltip-popup',
      'tooltip-left',
      'tooltip-right',
      'tooltip-top',
      'tooltip-bottom',
      'malix-doodle-popin',
      'tooltip-popup-charte',
      'price-pass-sold-out',
      'price-pass-availability',
      'price-pass-cta-row',
      'price-pass-complet-block',
      'stage-cta-complet-block',
      'stage-cta-complet-block--open-verso'
    ],
    greedy: [
      /^tooltip-/,
      /^match-slider-/,
      /^match-slide/
    ]
  }
};
