module.exports = {
  content: ['index.html', 'assets/js/script.js'],
  css: ['assets/css/style.css'],
  output: 'dist/assets/css/style.css',
  safelist: {
    standard: [
      'show',
      'open',
      'hidden',
      'active',
      'flipped',
      'hero-confetti',
      'hero-doodle-svg',
      'settle-final',
      'floating-doodle',
      'floating-doodle-inner',
      'floating-doodle-squashed',
      'is-visible',
      'titre-1',
      'titre-2',
      'titre-3',
      'text-charte',
      'description-charte',
      'slider-active',
      'match-slider-container',
      'match-slider-track',
      'match-slide',
      'match-slide-image',
      'match-slide-overlay',
      'match-slide-name',
      'match-slide-role',
      'match-slide-bio',
      'match-slider-close',
      'match-slider-dots',
      'match-slider-dot',
      'spectacle-single-slide',
      'match-slide-bg-right',
      'match-slide-bio-short',
      'match-slide-bio-full',
      'tooltip-overlay',
      'tooltip-popup',
      'tooltip-left',
      'tooltip-right',
      'tooltip-top',
      'tooltip-bottom'
    ],
    greedy: [
      /^tooltip-/,
      /^match-slider-/,
      /^match-slide/
    ]
  }
};
